# Generated by Django 3.2.16 on 2023-01-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=255)),
                ('batch', models.CharField(choices=[('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023')], default=2023, max_length=255)),
                ('cet', models.IntegerField(default=0)),
                ('comedk', models.IntegerField(default=0)),
                ('management', models.IntegerField(default=0)),
                ('diploma', models.IntegerField(default=0)),
                ('cob', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Admission',
            },
        ),
        migrations.CreateModel(
            name='AdmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='api.admission')),
            ],
        ),
    ]
