# Generated by Django 3.2.16 on 2023-04-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230125_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='cob_outgoing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admission',
            name='snq',
            field=models.IntegerField(default=0),
        ),
    ]
