# Generated by Django 3.2.16 on 2023-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230613_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultupload',
            name='loading',
        ),
        migrations.AddField(
            model_name='resultupload',
            name='uploading_done',
            field=models.BooleanField(default=True),
        ),
    ]
