# Generated by Django 3.2.16 on 2023-04-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230403_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='cob',
            new_name='cob_incoming',
        ),
    ]
