# Generated by Django 3.2.16 on 2023-04-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_cob_admission_cob_incoming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='semester',
        ),
        migrations.AddField(
            model_name='admission',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
