# Generated by Django 3.2.16 on 2023-07-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_templates_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
