# Generated by Django 3.2.16 on 2023-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230420_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
