# Generated by Django 3.2.16 on 2023-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_admission_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='cet',
            new_name='CET',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='cob_incoming',
            new_name='CoB_incoming',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='cob_outgoing',
            new_name='CoB_outgoing',
        ),
    ]
