# Generated by Django 3.2.16 on 2023-04-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230428_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='ETE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject',
            field=models.CharField(default='ABC', max_length=255),
            preserve_default=False,
        ),
    ]
