# Generated by Django 3.2.16 on 2023-05-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230428_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='branch',
        ),
    ]
