# Generated by Django 3.2.16 on 2023-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_studentprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
